---worker-tables

CREATE TABLE public."ORGANIZATION" (
  "ID" BIGINT  NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "ORG_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('ORG-' || "ID"::TEXT) STORED,
  "ORG_STATUS" CHARACTER VARYING(50),
  "ORG_TYPE" CHARACTER VARYING(50),
  "ORG_NAME" CHARACTER VARYING(150),
  "ORG_STATE" CHARACTER VARYING(50),
  "ORG_CREATEDBY" CHARACTER VARYING(50),
  "ORG_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ORG_UPDATEDBY" CHARACTER VARYING(50),
  "ORG_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ORG_ID")
);

CREATE TABLE public."AGENCY" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "AGY_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('AGY-' || "ID"::TEXT) STORED,
  "AGY_NAME" CHARACTER VARYING(150),
  "AGY_TYPE" CHARACTER VARYING(50),
  "AGY_STATUS" CHARACTER VARYING(50),
  "AGY_ORG_ID" CHARACTER VARYING(50),
  "AGY_CREATEDBY" CHARACTER VARYING(50),
  "AGY_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "AGY_UPDATEDBY" CHARACTER VARYING(50),
  "AGY_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("AGY_ID")
);

CREATE TABLE public."OFFICE" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "OFF_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('OFF-' || "ID"::TEXT) STORED,
  "OFF_AGY_ID" CHARACTER VARYING(50),
  "OFF_NAME" CHARACTER VARYING(150),
  "OFF_TYPE" CHARACTER VARYING(50),
  "OFF_STATUS" CHARACTER VARYING(50),
  "OFF_CNTY" CHARACTER VARYING(50),
  "OFF_CREATEDBY" CHARACTER VARYING(50),
  "OFF_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "OFF_UPDATEDBY" CHARACTER VARYING(50),
  "OFF_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("OFF_ID")
);

CREATE TABLE public."WORKER_OFFICE" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "WOF_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('WOF-' || "ID"::TEXT) STORED,
  "WOF_OFF_ID" CHARACTER VARYING(50),
  "WOF_WOR_ID" CHARACTER VARYING(50),
  "WOF_STRT_DTE" DATE,
  "WOF_END_DTE" DATE,
  "WOF_CREATEDBY" CHARACTER VARYING(50),
  "WOF_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "WOF_UPDATEDBY" CHARACTER VARYING(50),
  "WOF_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("WOF_ID")
);

CREATE TABLE public."WORKER" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "WOR_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('WOR-' || "ID"::TEXT) STORED,
  "WOR_USER_ID" CHARACTER VARYING(50),
  "WOR_EMPLOYEE_ID" CHARACTER VARYING(50),
  "WOR_TYPE" CHARACTER VARYING(50),
  "WOR_STATUS" CHARACTER VARYING(50),
  "WOR_CREATEDBY" CHARACTER VARYING(50),
  "WOR_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "WOR_UPDATEDBY" CHARACTER VARYING(50),
  "WOR_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("WOR_ID")
);

CREATE TABLE public."WORKER_ROLES" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "WRO_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('WRO-' || "ID"::TEXT) STORED,
  "WRO_ROL_ID" CHARACTER VARYING(50),
  "WRO_WOR_ID" CHARACTER VARYING(50),
  "WRO_CREATEDBY" CHARACTER VARYING(50),
  "WRO_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "WRO_UPDATED_BY" CHARACTER VARYING(50),
  "WRO_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("WRO_ID")
);

CREATE TABLE public."ROLES" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "ROL_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('ROL-' || "ID"::TEXT) STORED,
  "ROL_NAME" CHARACTER VARYING(150),
  "ROL_DESC" CHARACTER VARYING(250),
  "ROL_CREATEDBY" CHARACTER VARYING(50),
  "ROL_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ROL_UPDATEDBY" CHARACTER VARYING(50),
  "ROL_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ROL_ID")
);

CREATE TABLE public."USERS" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "USER_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('USER-' || "ID"::TEXT) STORED,
  "USER_FIRST_NAME" CHARACTER VARYING(150),
  "USER_MIDDLE_NAME" CHARACTER VARYING(150),
  "USER_LAST_NAME" CHARACTER VARYING(50),
  "USER_EMAIL" CHARACTER VARYING(150),
  "USER_PHONE" CHARACTER VARYING(50),
  "USER_TYPE" CHARACTER VARYING(50),
  "USER_STATUS" CHARACTER VARYING(50),
  "USER_UPDATEDBY" CHARACTER VARYING(50),
  "USER_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "USER_CREATEDBY" CHARACTER VARYING(50),
  "USER_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("USER_ID")
);

CREATE TABLE public."WORKER_SPECIALITY" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "WSP_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('WSP-' || "ID"::TEXT) STORED,
  "WSP_SSK_ID" CHARACTER VARYING(50),
  "WSP_WOR_ID" CHARACTER VARYING(50),
  "WSP_CREATEDBY" CHARACTER VARYING(50),
  "WSP_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "WSP_UPDATED_BY" CHARACTER VARYING(50),
  "WSP_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("WSP_ID")
);

CREATE TABLE public."SPECIALITY_SKILLSET" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "SSK_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('SSK-' || "ID"::TEXT) STORED,
  "SSK_SKILLSET" CHARACTER VARYING(250),
  "SSK_DESC" CHARACTER VARYING(250),
  "SSK_CREATEDBY" CHARACTER VARYING(50),
  "SSK_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "SSK_UPDATEDBY" CHARACTER VARYING(50),
  "SSK_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("SSK_ID")
);

---Case tables

CREATE TABLE public."CASE" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "CASE_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('CASE-' || "ID"::TEXT) STORED,
  "CASE_TYPE" CHARACTER VARYING(50),
  "CASE_STATUS" CHARACTER VARYING(50),
  "CASE_TRACKING_NUM" CHARACTER VARYING(50),
  "CASE_FUNC" CHARACTER VARYING(50),
  "CASE_TRNS_DTE" DATE,
  "CASE_TRNS_RSN" CHARACTER VARYING(250),
  "CASE_CLSD_DTE" DATE,
  "CASE_CLSD_RSN" CHARACTER VARYING(250),
  "CASE_SUSP_DTE" DATE,
  "CASE_SUSP_RSN" CHARACTER VARYING(250),
  "CASE_FVL_ID" CHARACTER VARYING(50),
  "CASE_ADDR_SUPRESS_IND" BIT(1),
  "CASE_WOR_ID" CHARACTER VARYING(50),
  "CASE_CREATEDBY" CHARACTER VARYING(50),
  "CASE_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CASE_UPDATEDBY" CHARACTER VARYING(50),
  "CASE_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("CASE_ID")
);

CREATE TABLE public."FAMILY_VIOLENCE" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "FVL_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('FVL-' || "ID"::TEXT) STORED,
  "FVL_EFFECTIVE_START_DTE" DATE,
  "FVL_EFFECTIVE_END_DTE" DATE,
  "FVL_VIOLENCE_IND" BIT(1),
  "FVL_VIOLENCE_TYPE" CHARACTER VARYING(50),
  "FVL_CONFIDENTIALITY" CHARACTER VARYING(50),
  "FVL_PROTECTIVE_ORDER_IND" BIT(1),
  "FVL_SAFETY_CONCERNS" CHARACTER VARYING(50),
  "FVL_NCP_ADD_INFO" CHARACTER VARYING(250),
  "FVL_CREATEDBY" CHARACTER VARYING(50),
  "FVL_UPDATED_BY" CHARACTER VARYING(50),
  "FVL_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "FVL_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("FVL_ID")
);

CREATE TABLE public."CASE_PERSON_RELATIONSHIP" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "CPE_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('CPE-' || "ID"::TEXT) STORED,
  "CPE_PRS_ID" CHARACTER VARYING(50),
  "CPE_CASE_ID" CHARACTER VARYING(50),
  "CPE_CASE_RELSHP" CHARACTER VARYING(50),
  "CPE_CHILD_RELSHP" CHARACTER VARYING(50),
  "CPE_CREATEDBY" CHARACTER VARYING(50),
  "CPE_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CPE_UPDTEDBY" CHARACTER VARYING(50),
  "CPE_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("CPE_ID")
);

---order-tables

CREATE TABLE public."ORDER_HEADER" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "ORH_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('ORH-' || "ID"::TEXT) STORED,
  "ORH_CASE_ID" CHARACTER VARYING(50),
  "ORH_PRS_ID" CHARACTER VARYING(50),
  "ORH_INFO_TXT" CHARACTER VARYING(250),
  "ORH_DOCKET_NUM" CHARACTER VARYING(50),
  "ORH_EFFICTIVE_DATE" DATE,
  "ORH_AMOUNT" MONEY,
  "ORH_PAYMENT_TERM" CHARACTER VARYING(50),
  "ORH_PAST_DUE" CHARACTER VARYING(50),
  "ORH_TYPE" CHARACTER VARYING(50),
  "ORH_STATUS" CHARACTER VARYING(50),
  "ORH_CREATEDBY" CHARACTER VARYING(50),
  "ORH_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ORH_UPDATED_BY" CHARACTER VARYING(50),
  "ORH_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ORH_ID")
);

--person-tables

CREATE TABLE public."PERSON" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PRS_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PRS-' || "ID"::TEXT) STORED,
  "PRS_PREFIX" CHARACTER VARYING(50),
  "PRS_FNAME" CHARACTER VARYING(150),
  "PRS_MNAME" CHARACTER VARYING(150),
  "PRS_LNAME" CHARACTER VARYING(150),
  "PRS_SUFFIX" CHARACTER VARYING(50),
  "PRS_PREFERRED_NAME" CHARACTER VARYING(150),
  "PRS_MAIDEN_NAME" CHARACTER VARYING(150),
  "PRS_BRTH_DTE" DATE,
  "PRS_GENDER" CHARACTER VARYING(50),
  "PRS_BRTH_CITY" CHARACTER VARYING(50),
  "PRS_BRTH_CNTY" CHARACTER VARYING(50),
  "PRS_BRTH_ST" CHARACTER VARYING(50),
  "PRS_BRTH_PROV" CHARACTER VARYING(50),
  "PRS_BRTH_CNTRY" CHARACTER VARYING(50),
  "PRS_OCCUPATION" CHARACTER VARYING(150),
  "PRS_SSN" INTEGER,
  "PRS_SSN_TYPE" CHARACTER VARYING(50),
  "PRS_SSN_VERIFIED_IND" BIT(1),
  "PRS_SSN_VERIFIED_DTE" DATE,
  "PRS_ITIN" INTEGER,
  "PRS_DTH_DTE" DATE,
  "PRS_DTH_PLCE" CHARACTER VARYING(150),
  "PRS_CREATEDBY" CHARACTER VARYING(50),
  "PRS_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PRS_UPDATEDBY" CHARACTER VARYING(50),
  "PRS_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PRS_ID")
);

CREATE TABLE public."PERSON_EMPLOYMENT_INFO" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PEM_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PEM-' || "ID"::TEXT) STORED,
  "PEM_PRS_ID" CHARACTER VARYING(50),
  "PEM_LEM_ID" CHARACTER VARYING(50),
  "PEM_FROM_DTE" DATE,
  "PEM_TO_DTE" DATE,
  "PEM_TYPE" CHARACTER VARYING(50),
  "PEM_STATUS" CHARACTER VARYING(50),
  "PEM_EARNED_AMT" MONEY,
  "PEM_DESC" CHARACTER VARYING(50),
  "PEM_HRLY_PAY_AMT" MONEY,
  "PEM_HRS_WRKED_PER_WK" CHARACTER VARYING(50),
  "PEM_1ST_PAY_DTE" DATE,
  "PEM_PYMT_FREQ" CHARACTER VARYING(50),
  "PEM_WHLDING_IN_PL_IND" BIT(1),
  "PEM_VLNTRY_WHLDING_IND" BIT(1),
  "PEM_EMP_VERIFIED_IND" BIT(1),
  "PEM_EMP_VERIFIED_DTE" DATE,
  "PEM_EMP_ENDED_IND" BIT(1),
  "PEM_EMP_ENDED_DTE" DATE,
  "PEM_EMP_PAYRL_NUM" CHARACTER VARYING(50),
  "PEM_CREATEDBY" CHARACTER VARYING(50),
  "PEM_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PEM_UPDATEDBY" CHARACTER VARYING(50),
  "PEM_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PEM_ID")
);

CREATE TABLE public."PERSON_SPECIAL_ASSISTANCE" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PSA_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PSA-' || "ID"::TEXT) STORED,
  "PSA_PRS_ID" CHARACTER VARYING(50),
  "PSA_ASSISTANCE_DESC" CHARACTER VARYING(250),
  "PSA_CREATEDBY" CHARACTER VARYING(50),
  "PSA_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PSA_UPDATEDBY" CHARACTER VARYING(50),
  "PSA_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PSA_ID")
);

CREATE TABLE public."UNEARNED_INCOME" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "UIN_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('UIN-' || "ID"::TEXT) STORED,
  "UIN_PRS_ID" CHARACTER VARYING(50),
  "UIN_TYPE" CHARACTER VARYING(50),
  "UIN_AMT" MONEY,
  "UIN_DESC" CHARACTER VARYING(250),
  "UIN_STRT_DTE" DATE,
  "UIN_END_DTE" DATE,
  "UIN_CLAIM_NUM" CHARACTER VARYING(50),
  "UIN_CLAIM_PENDING_DTE" DATE,
  "UIN_FREQ" CHARACTER VARYING(50),
  "UIN_GRNSH_RQST_DTE" DATE,
  "UIN_GRNSH_AMT" MONEY,
  "UIN_GRNSH_DTE" DATE,
  "UIN_GRNSH_RELS_RQST_DTE" DATE,
  "UIN_GRNSH_RELS_DTE" DATE,
  "UIN_STATUS" CHARACTER VARYING(50),
  "UIN_CREATEDBY" CHARACTER VARYING(50),
  "UIN_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UIN_UPDATEDBY" CHARACTER VARYING(50),
  "UIN_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("UIN_ID")
);

CREATE TABLE public."PERSON_ASSETS" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PAS_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PAS-' || "ID"::TEXT) STORED,
  "PAS_PRS_ID" CHARACTER VARYING(50),
  "PAS_TYPE" CHARACTER VARYING(50),
  "PAS_PURCHASE_DTE" DATE,
  "PAS_SALE_DTE" DATE,
  "PAS_MAKE" CHARACTER VARYING(50),
  "PAS_MODEL" CHARACTER VARYING(50),
  "PAS_YEAR" INTEGER,
  "PAS_DESC" CHARACTER VARYING(250),
  "PAS_STATUS" CHARACTER VARYING(50),
  "DISPOSAL_AMT" MONEY,
  "PAS_BANK_BRANCH_NAME" CHARACTER VARYING(250),
  "PAS_BANK_ACCOUNT" INTEGER,
  "PAS_BANK_CLSD_DTE" DATE,
  "PAS_BANK_CLSD_RSN" CHARACTER VARYING(50),
  "PAS_CREATEDBY" CHARACTER VARYING(50),
  "PAS_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PAS_UPDATEDBY" CHARACTER VARYING(50),
  "PAS_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PAS_ID")
);

CREATE TABLE public."PERSON_EDUCATION_INFO" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PED_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PED-' || "ID"::TEXT) STORED,
  "PED_PRS_ID" CHARACTER VARYING(50),
  "PED_LSC_ID" CHARACTER VARYING(50),
  "PED_GRAD_DTE" DATE,
  "PED_ENROLL_VERIFIED_IND" BIT(1),
  "PED_STATUS" CHARACTER VARYING(50),
  "PED_TYPE" CHARACTER VARYING(50),
  "PED_CREATEDBY" CHARACTER VARYING(50),
  "PED_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PED_UPDATEDBY" CHARACTER VARYING(50),
  "PED_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PED_ID")
);

CREATE TABLE public."LOOKUP_SCHOOL" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "LSC_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('LSC-' || "ID"::TEXT) STORED,
  "LSC_SCHOOL_NAME" CHARACTER VARYING(250),
  "LSC_CREATEDBY" CHARACTER VARYING(50),
  "LSC_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LSC_UPDATEDBY" CHARACTER VARYING(50),
  "LSC_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("LSC_ID")
);

CREATE TABLE public."LOOKUP_EMPLOYER" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "LEM_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('LEM-' || "ID"::TEXT) STORED,
  "LEM_EMPLOYER_NAME" CHARACTER VARYING(50),
  "LEM_INDIAN_OWN_IND" BIT(1),
  "LEM_TRIBE_OWN_IND" BIT(1),
  "LEM_TRIBAL_MBR_OWN_IND" BIT(1),
  "LEM_FEIN_NUM" CHARACTER VARYING(50),
  "LEM_SEIN_NUM" CHARACTER VARYING(50),
  "LEM_RESV_TXT" CHARACTER VARYING(200),
  "LEM_CREATEDBY" CHARACTER VARYING(50),
  "LEM_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LEM_UPDATEDBY" CHARACTER VARYING(50),
  "LEM_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("LEM_ID")
);

CREATE TABLE public."PERSON_MILITARY_STATUS" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PMI_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PMI-' || "ID"::TEXT) STORED,
  "PMI_PRS_ID" CHARACTER VARYING(50),
  "PMI_TYPE" CHARACTER VARYING(50),
  "PMI_STATUS" CHARACTER VARYING(50),
  "PMI_STRT_DTE" DATE,
  "PMI_END_DTE" DATE,
  "PMI_SRL_NUM" CHARACTER VARYING(50),
  "PMI_CREATEDBY" CHARACTER VARYING(50),
  "PMI_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PMI_UPDATEDBY" CHARACTER VARYING(50),
  "PMI_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PMI_ID")
);

CREATE TABLE public."PERSON_LOCATE" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PLO_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PLO-' || "ID"::TEXT) STORED,
  "PLO_PRS_ID" CHARACTER VARYING(50),
  "PLO_TYPE" CHARACTER VARYING(50),
  "PLO_DESC" CHARACTER VARYING(250),
  "PLO_REQUEST_DTE" DATE,
  "PLO_RESPONSE_DTE" DATE,
  "PLO_DISPOSITION" CHARACTER VARYING(50),
  "PLO_DISPOSITION_DTE" DATE,
  "PLO_STATUS" CHARACTER VARYING(50),
  "PLO_CREATEDBY" CHARACTER VARYING(50),
  "PLO_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PLO_UPDATEDBY" CHARACTER VARYING(50),
  "PLO_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PLO_ID")
);

CREATE TABLE public."PERSON_MARITAL_INFO" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PMA_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PMA-' || "ID"::TEXT) STORED,
  "PMA_PRS_ID" CHARACTER VARYING(50),
  "PMA_TYPE" CHARACTER VARYING(50),
  "PMA_STATUS" CHARACTER VARYING(50),
  "PMA_MARRIED_DTE" DATE,
  "PMA_MARRIED_CITY" CHARACTER VARYING(50),
  "PMA_DIVORCE_DTE" DATE,
  "PMA_SEPERATED_DTE" DATE,
  "PMA_MULTIPLE_MARRIAGES_IND" BIT(1),
  "PMA_CREATEDBY" CHARACTER VARYING(50),
  "PMA_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PMA_UPDATEDBY" CHARACTER VARYING(50),
  "PMA_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PMA_ID")
);

CREATE TABLE public."PERSON_DEMOGRAPHICS" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PDE_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PDE-' || "ID"::TEXT) STORED,
  "PDE_PRS_ID" CHARACTER VARYING(50),
  "PDE_WT_LBS" CHARACTER VARYING(3),
  "PDE_WT_OUNCE" CHARACTER VARYING(5),
  "PDE_HT_FT" CHARACTER VARYING(4),
  "PDE_HT_INCH" CHARACTER VARYING(4),
  "PDE_EYE_COLR" CHARACTER VARYING(50),
  "PDE_HAIR_COLR" CHARACTER VARYING(50),
  "PDE_DISTNG_MRKS" CHARACTER VARYING(250),
  "PDE_CREATEDBY" CHARACTER VARYING(50),
  "PDE_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PDE_UPDATEDBY" CHARACTER VARYING(50),
  "PDE_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PDE_ID")
);

CREATE TABLE public."PERSON_ARREST" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PAR_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PAR-' || "ID"::TEXT) STORED,
  "PAR_PRS_ID" CHARACTER VARYING(50),
  "PAR_DTE" DATE,
  "PAR_RSN" CHARACTER VARYING(250),
  "PAR_CITY" CHARACTER VARYING(50),
  "PAR_CNTY" CHARACTER VARYING(50),
  "PAR_PROV" CHARACTER VARYING(50),
  "PAR_ST" CHARACTER VARYING(50),
  "PAR_CNTRY" CHARACTER VARYING(50),
  "PAR_CONV_DTE" DATE,
  "PAR_CREATEDBY" CHARACTER VARYING(50),
  "PAR_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PAR_UPDATEDBY" CHARACTER VARYING(50),
  "PAR_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PAR_ID")
);

CREATE TABLE public."PERSON_RACE" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PRA_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PRA-' || "ID"::TEXT) STORED,
  "PRA_PRS_ID" CHARACTER VARYING(50),
  "PRA_RACE" CHARACTER VARYING(50),
  "PRA_CREATEDBY" CHARACTER VARYING(50),
  "PRA_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PRA_UPDATEDBY" CHARACTER VARYING(50),
  "PRA_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PRA_ID")
);

CREATE TABLE public."PERSON_PROBATION" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PPR_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PPR-' || "ID"::TEXT) STORED,
  "PPR_PRS_ID" CHARACTER VARYING(50),
  "PPR_STRT_DTE" DATE,
  "PPR_END_DTE" DATE,
  "PPR_TYPE" CHARACTER VARYING(50),
  "PPR_OFCR_BTCH_NUM" CHARACTER VARYING(50),
  "PPR_CREATEDBY" CHARACTER VARYING(50),
  "PPR_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PPR_UPDATEDBY" CHARACTER VARYING(50),
  "PPR_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PPR_ID")
);

CREATE TABLE public."PERSON_ETHNICITY" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PET_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PET-' || "ID"::TEXT) STORED,
  "PET_PRS_ID" CHARACTER VARYING(50),
  "PET_ETHNICITY" CHARACTER VARYING(50),
  "CPE_CREATEDBY" CHARACTER VARYING(50),
  "CPE_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CPE_UPDATEDBY" CHARACTER VARYING(50),
  "CPE_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PET_ID")
);

CREATE TABLE public."PERSON_INCARCERATION" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PIN_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PIN-' || "ID"::TEXT) STORED,
  "PIN_PRS_ID" CHARACTER VARYING(50),
  "PIN_LCO_ID" CHARACTER VARYING(50),
  "PIN_INMATE_NUM" CHARACTER VARYING(50),
  "PIN_DTE" DATE,
  "PIN_RELS_DTE" DATE,
  "PIN_TRANS_DTE" DATE,
  "PIN_WRK_RELS_IND" BIT(1),
  "PIN_WRK_RELS_DTE" DATE,
  "PIN_PAROLE_ELGBL_DTE" DATE,
  "PIN_CREATEDBY" CHARACTER VARYING(50),
  "PIN_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PIN_UPDATEDBY" CHARACTER VARYING(50),
  "PIN_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PIN_ID")
);

CREATE TABLE public."LOOKUP_CORRECTIONAL_FACILITY" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "LCO_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('LCO-' || "ID"::TEXT) STORED,
  "LCO_CORRECTIONAL_FACILITY_NAME" CHARACTER VARYING(50),
  "LCO_TYPE" CHARACTER VARYING(50),
  "LCO_CREATEDBY" CHARACTER VARYING(50),
  "LCO_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LCO_UPDATEDBY" CHARACTER VARYING(50),
  "LCO_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("LCO_ID")
);

CREATE TABLE public."PERSON_PARENT" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PPA_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PPA-' || "ID"::TEXT) STORED,
  "PPA_PRS_ID" CHARACTER VARYING(50),
  "PPA_TYPE" CHARACTER VARYING(50),
  "PPA_PREFIX" CHARACTER VARYING(50),
  "PPA_FNAME" CHARACTER VARYING(50),
  "PPA_MNAME" CHARACTER VARYING(50),
  "PPA_LNAME" CHARACTER VARYING(50),
  "PPA_SUFFIX" CHARACTER VARYING(50),
  "PPA_BRTH_DTE" DATE,
  "PPA_DECEASED_IND" BIT(1),
  "PPA_DECEASED_DTE" DATE,
  "PPA_CREATEDBY" CHARACTER VARYING(50),
  "PPA_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PPA_UPDATEDBY" CHARACTER VARYING(50),
  "PPA_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PPA_ID")
);

CREATE TABLE public."PERSON_GRANT" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PGR_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PGR-' || "ID"::TEXT) STORED,
  "PGR_PRS_ID" CHARACTER VARYING(50),
  "PGR_GRNT_EFF_DTE" DATE,
  "PGR_GRNT_END_DTE" DATE,
  "PGR_GRNT_AMT" MONEY,
  "PGR_COOP_DTE" DATE,
  "PGR_NON_COOP_SANCTION_DTE" DATE,
  "PGR_RCPNT_COMP_IND" BIT(1),
  "PGR_TANF_RCPNT_IND" BIT(1),
  "PGR_NON_COOP_PRPSD_DT" DATE,
  "PGR_PREV_BENFT_RCVD_TXT" CHARACTER VARYING(50),
  "PGR_FRMR_TANF_RCPNT_IND" BIT(1),
  "PGR_UNREIMB_ASST_AMT" MONEY,
  "PGR_NON_COOP_DTE" DATE,
  "PGR_NON_COOP_RSN_TXT" CHARACTER VARYING(250),
  "PGR_FREQ" CHARACTER VARYING(50),
  "PGR_TOTAL_AMT" MONEY,
  "PGR_CREATEDBY" CHARACTER VARYING(50),
  "PGR_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PGR_UPDATEDBY" CHARACTER VARYING(50),
  "PGR_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PGR_ID")
);

CREATE TABLE public."PERSON_PAROLE" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PPA_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PPA-' || "ID"::TEXT) STORED,
  "PPA_PRS_ID" CHARACTER VARYING(50),
  "PPA_STRT_DTE" DATE,
  "PPA_END_DTE" DATE,
  "PPA_ERLY_RSLE_DTE" DATE,
  "PPA_ERLY_RSLE_RSN" CHARACTER VARYING(300),
  "PPA_CREATEDBY" CHARACTER VARYING(50),
  "PPA_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PPA_UPDATEDBY" CHARACTER VARYING(50),
  "PPA_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PPA_ID")
);

CREATE TABLE public."PERSON_LANGUAGE" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PLA_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PLA-' || "ID"::TEXT) STORED,
  "PLA_PRS_ID" CHARACTER VARYING(50),
  "PLA_LANGUAGE" CHARACTER VARYING(50),
  "PLA_CREATEDBY" CHARACTER VARYING(50),
  "PLA_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PLA_UPDATEDBY" CHARACTER VARYING(50),
  "PLA_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PLA_ID")
);

CREATE TABLE public."PERSON_LICENSE" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PLI_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PLI-' || "ID"::TEXT) STORED,
  "PLI_PRS_ID" CHARACTER VARYING(50),
  "PLI_NUMBER" CHARACTER VARYING(50),
  "PLI_STATE" CHARACTER VARYING(50),
  "PLI_STRT_DTE" DATE,
  "PLI_EXPIR_DTE" DATE,
  "PLI_JRSDCT_TXT" CHARACTER VARYING(50),
  "PLI_TRIBE_TXT" CHARACTER VARYING(50),
  "PLI_TYPE" CHARACTER VARYING(50),
  "PLI_STATUS" CHARACTER VARYING(50),
  "PLI_CREATEDBY" CHARACTER VARYING(50),
  "PLI_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PLI_UPDATEDBY" CHARACTER VARYING(50),
  "PLI_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PLI_ID")
);

--common-tables

CREATE TABLE public."ADDRESS" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "ADRS_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('ADRS-' || "ID"::TEXT) STORED,
  "ADRS_ST1" CHARACTER VARYING(200),
  "ADRS_ST2" CHARACTER VARYING(200),
  "ADRS_APTSUITE_NO" CHARACTER VARYING(50),
  "ADRS_CITY_ID" CHARACTER VARYING(50),
  "ADRS_ST_ID" CHARACTER VARYING(50),
  "ADRS_CNTY_ID" CHARACTER VARYING(50),
  "ADRS_ZIP_CD" CHARACTER VARYING(50),
  "ADRS_PROVINCE_ID" CHARACTER VARYING(100),
  "ADRS_CNTRY_ID" CHARACTER VARYING(50),
  "ADRS_RSVN" CHARACTER VARYING(100),
  "ADRS_DESC" CHARACTER VARYING(250),
  "ADRS_TYPE_ID" CHARACTER VARYING(50),
  "ADRS_STATUS_ID" CHARACTER VARYING(50),
  "ADRS_VERIFIED_IND" BIT(1),
  "ADRS_SUBJECT_AREA" CHARACTER VARYING(250),
  "ADRS_TABLE_NM" CHARACTER VARYING(50),
  "ADRS_KEY_COLUMN_NM" CHARACTER VARYING(50),
  "ADRS_KEY_COLUMN_VALUE" CHARACTER VARYING(50),
  "ADRS_FRM_DTE" DATE,
  "ADRS_TO_DTE" DATE,
  "ADRS_CREATEDBY" CHARACTER VARYING(50),
  "ADRS_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ADRS_UPDATED_BY" CHARACTER VARYING(50),
  "ADRS_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ADRS_ID")
);

CREATE TABLE public."CONTACT" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "CON_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('CON-' || "ID"::TEXT) STORED,
  "CON_TYPE_ID" CHARACTER VARYING(50),
  "CON_STATUS_ID" CHARACTER VARYING(50),
  "CON_SUBJECT_AREA" CHARACTER VARYING(250),
  "CON_TABLE_NM" CHARACTER VARYING(50),
  "CON_KEY_COLUMN_NAME" CHARACTER VARYING(50),
  "CON_KEY_COLUMN_VALUE" CHARACTER VARYING(50),
  "CON_CREATEDBY" CHARACTER VARYING(50),
  "CON_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CON_UPDATEDBY" CHARACTER VARYING(50),
  "CON_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("CON_ID")
);

---parentage-tables

CREATE TABLE public."PARENTAGE" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PAT_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PAT-' || "ID"::TEXT) STORED,
  "PAT_CPE_ID" CHARACTER VARYING(50),
  "PAT_ESTB_IND" BIT(1),
  "PAT_ESTB_DTE" DATE,
  "PAT_ESTB_CITY" CHARACTER VARYING(50),
  "PAT_ESTB_CNTY" CHARACTER VARYING(50),
  "PAT_ESTB_ST" CHARACTER VARYING(50),
  "PAT_ESTB_DOCKET_NUMBER" CHARACTER VARYING(50),
  "PAT_ESTB_MTHD_TXT" CHARACTER VARYING(50),
  "PAT_DUE_DTE" DATE,
  "PAT_CONCPT_DTE" DATE,
  "PAT_CONCPT_END_DTE" DATE,
  "PAT_CREATEDBY" CHARACTER VARYING(50),
  "PAT_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PAT_UPDATEDBY" CHARACTER VARYING(50),
  "PAT_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PAT_ID")
);

CREATE TABLE public."PERSON_SEX_RELSHP" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PSR_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PSR-' || "ID"::TEXT) STORED,
  "PSR_PAT_ID" CHARACTER VARYING(50),
  "PSR_RELTN_BEGAN_CITY" CHARACTER VARYING(50),
  "PSR_RELTN_BEGAN_CNTY" CHARACTER VARYING(50),
  "PSR_RELTN_BEGAN_ST" CHARACTER VARYING(50),
  "PSR_RELTN_BEGAN_DTE" DATE,
  "PSR_RELTN_ENDED_CITY" CHARACTER VARYING(50),
  "PSR_RELTN_ENDED_CNTY" CHARACTER VARYING(50),
  "PSR_RELTN_ENDED_ST" CHARACTER VARYING(50),
  "PSR_RELTN_ENDED_DTE" DATE,
  "PSR_CREATEDBY" CHARACTER VARYING(50),
  "PSR_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PSR_UPDATEDBY" CHARACTER VARYING(50),
  "PSR_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PSR_ID")
);

CREATE TABLE public."PERSON_GEN_TEST" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "PGT_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('PGT-' || "ID"::TEXT) STORED,
  "PGT_CPE_ID" CHARACTER VARYING(50),
  "PGT_GENLAB_ID" CHARACTER VARYING(50),
  "PGT_PAT_ID" CHARACTER VARYING(50),
  "PGT_DTE" DATE,
  "PGT_TM_DTE" DATE,
  "PGT_RSLTS_TXT" CHARACTER VARYING(150),
  "PGT_RSLTS_DTE" DATE,
  "PGT_ORDED_DTE" DATE,
  "PGT_DISP_TXT" CHARACTER VARYING(150),
  "PGT_TYPE" CHARACTER VARYING(50),
  "PGT_CREATEDBY" CHARACTER VARYING(50),
  "PGT_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PGT_UPDATEDBY" CHARACTER VARYING(50),
  "PGT_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("PGT_ID")
);

CREATE TABLE public."LOOKUP_GENETIC_TEST_LAB" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "GENLAB_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('GENLAB-' || "ID"::TEXT) STORED,
  "GENLAB_NAME" CHARACTER VARYING(50),
  "GENLAB_DIRIONS_TXT" CHARACTER VARYING(150),
  "GENLAB_CREATEDBY" CHARACTER VARYING(50),
  "GENLAB_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "GENLAB_UPDATEDBY" CHARACTER VARYING(50),
  "GENLAB_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("GENLAB_ID")
);

CREATE TABLE "SHARED_NOTES" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "NOTE_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('NOTE-' || "ID"::TEXT) STORED,
  "NOTE_TYPE" CHARACTER VARYING(37),
  "NOTE_STATUS" CHARACTER VARYING(37),
  "NOTE_SUBJECT_AREA" CHARACTER VARYING(100),
  "NOTE_TABLE_NAME" CHARACTER VARYING(100),
  "NOTE_KEY_COLUMN_NAME" CHARACTER VARYING(100),
  "NOTE_KEY_VALUE" CHARACTER VARYING(100),
  "NOTE_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "NOTE_TXT" CHARACTER VARYING(100),
  "NOTE_CREATEDBY" CHARACTER VARYING(50),
  "NOTE_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "NOTE_UDATEDBY" CHARACTER VARYING(50),
  "NOTE_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("NOTE_ID")
);

CREATE TABLE "SHARED_DOCUMENT" (
  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  "DOC_ID" CHARACTER VARYING(30) GENERATED ALWAYS AS ('DOC-' || "ID"::TEXT) STORED,
  "DOC_TYPE" CHARACTER VARYING(30),
  "DOC_STATUS" CHARACTER VARYING(30),
  "DOC_SUBJECT_AREA" CHARACTER VARYING(30),
  "DOC_TABLE_NAME" CHARACTER VARYING(30),
  "DOC_KEY_COLUMN_NAME" CHARACTER VARYING(30),
  "DOC_KEY_VALUE" CHARACTER VARYING(30),
  "DOC_UPLOAD_DATE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "DOC_UPLOAD_LOCATION" CHARACTER VARYING(30),
  "DOC_CREATEDBY" CHARACTER VARYING(50),
  "DOC_UPDATEDBY" CHARACTER VARYING(50),
  "DOC_CREATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "DOC_UPDATED_DTE" TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("DOC_ID")
);


